version: '3.8'
services:
  app: 
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: nasa-app-image
    container_name: nasa_app
    ports: 
      - 4000:3000
    depends_on: 
      - redis
      - mongo

  mongo:
    image: mongo:latest
    container_name: nasa_mongo
    volumes: 
    - nasa_data:/data/db

  redis:
    image: redis:alpine
    container_name: nasa_redis

volumes:
  nasa_data: