# from command
FROM node:18-alpine3.19

# expose a port
EXPOSE 3000

# add  a command CMD
CMD ["npm", "run", "dev"]

# change the directory with workdir
WORKDIR /app

# copy the code to the container
COPY package.json .

RUN npm install && apk add --no-cache curl

# RUN install the packages
COPY . .

HEALTHCHECK --interval=15s --timeout=10s --start-period=10s --retries=3 \
  CMD curl -f http://localhost:3000/health